import { TALENTS_DEMON_HUNTER } from 'common/TALENTS';

export const IMPROVE_CONSUME_CAST_TIME_REDUCTION_SECONDS = 0.25;

export const FAKE_VOIDBLADE_CAST_ID = 1245414;
export const FAKE_THEHUNT_CAST_ID = 1246169;

export const VIOLENT_TRANSFORMATION_AFFECTED_SPELLS = [
  TALENTS_DEMON_HUNTER.VOIDBLADE_TALENT,
  TALENTS_DEMON_HUNTER.THE_HUNT_DEVOURER_TALENT,
];
